### ISSUE TITLE
High CPU usage after KeepassXC clear clipboard

### ISSUE THREAD

**Issue by tamara-schmitz** [AgathaSorceress/url-eater#3]
I'm gonna need to collect more information about what exactly is going on but here is the information I have so far:

When you copy a password from KeepassXC, your clipboard will be cleared after X amount of time. When that happens url-eater seems to be going into a busy state. 

Here are the top three processes in `top`. 100% CPU is the equivalent of 100% on one CPU core of many on an SMP system.

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                  
29492 tamara    20   0   71,7m   3,9m   3,4m R 62,46 0,024   1:16.30 url-eater                                                                                
10330 tamara    20   0  266,1m 120,6m  80,3m S 59,47 0,762   3:58.94 Xwayland                                                                                 
10039 tamara    20   0 5177,2m 696,9m 212,7m S 8,306 4,405  17:23.96 gnome-shell
```

The CPU usage goes down again once I copy any random string into my clipboard.

System Information:
DE: GNOME 44.3 on Wayland
OS: openSUSE Tumbleweed 20230729
Build: Based on commit 9f04250
https://build.opensuse.org/package/show/home:tschmitz/url-eater

**Comment by tamara-schmitz** [comment]
This is why right?

https://github.com/AgathaSorceress/url-eater/blob/9f042508ee76b6920923c97ab39318e7075fde0e/src/main.rs#L49

https://github.com/AgathaSorceress/url-eater/blob/9f042508ee76b6920923c97ab39318e7075fde0e/src/main.rs?#L65

How about at the beginning of the loop there is a lil eep? Like say 0.25 seconds? Should be fast enough I hope.

But I don't understand why CPU usage is so low, when there IS something in the clipboard. 😵‍

**Comment by tamara-schmitz** [comment]
I think
https://github.com/allie-wake-up/cli-clipboard/blob/545878acf67047c699a52c8f37a9dbb978c6c536/src/x11_clipboard.rs?#L56
calls
https://github.com/quininer/x11-clipboard/blob/c7fd2a93c93a7690478953db87de849d47ce9f2a/src/lib.rs?#L273
with a timeout of 3 seconds.
Might be better if that crate called [load_wait](https://docs.rs/x11-clipboard/latest/x11_clipboard/struct.Clipboard.html?#method.load_wait) instead no?

**Comment by tamara-schmitz** [comment]
So perhaps something like: when empty, sleep 0.25s, then continue the loop would be a cool implementation.

**Comment by AgathaSorceress** [comment]
I pushed the changes to the [fix-empty-clipboard](https://github.com/AgathaSorceress/url-eater/tree/fix-empty-clipboard) branch. Let me know if that fixes it

**Comment by tamara-schmitz** [comment]
Yes! It does help! No longer see the issue on my setup.

Btw I said 0.25s in the hopes that it's still responsive enough for most people.

**Comment by AgathaSorceress** [comment]
Alright, I've merged the fix into the main branch. I might make the 250ms sleep shorter in the future, but so far it seems to work well enough.
